#import "../things-to-add.typ":*

= FLRW Metric

This section is based on @katanaev-killing-fields-homogeneous-and-isotropic and
@riemannian-manifolds-lee.

In cosmology the most widely used metric to describe spacetime at big scales 
is is the FLRW (Friedmann Lemaitre Robertson Walker) metric. Even in contexts where general relativity is modified this
is the case, this is because the principles that lead towards this metric are, 
to some degree, independent of general relativity. 

The fundamental principle behind this metric is the observed homogeneity and
isotropy of the universe at big scales. In more formal terms this means that
there have to be a family of spacelike surfaces that are isometric
under translations in all spatial directions and rotations around any point. This
is, there are a family of spatial slices that are maximally symmetric so that 
for any point in the manifold is part of one of the slices.

The usual ways to write this metric are

$ 
  dd(s)^2 &= -dd(t)^2 + a^2(t)(dd(r)^2/sqrt(1 - k r^2) + r^2 dd(Omega)^2)\
          &= -dd(t)^2 + a^2(t)(dd(chi)^2 + S_k^2 (chi) dd(Omega)^2)
$

Where $chi$ is the comoving distance, $dd(Omega)$ represents the angular part
of the metric and $a(t)$ is the so called scale factor and whose value is obtained 
via the Einstein field equations in general relativity or the equations of motion 
of the metric in other gravitational theories.

Since this is going to be a math intensive chapter here an outline of how to 
prove the form of the metric is outlined here.

+ First prove that the metric is separable, meaning $dd(s)^2 = -dd(t)^2 + g_(i j) 
dd(x)^i dd(x)^j$ and then prove that $dd(s)^2 = -dd(t)^2 + a^2(t) h_(i j)$ where $h$ is independent of time
+ After this prove that since $t = cte$ are maximally submanifolds $g_(i j)$ is a constant sectional curvature space
+ By applying the Killing-Hopf theorem @riemannian-manifolds-lee the spatial submanifolds have to be isometric to a 4-sphere, 4-hyperboloid or a flat space.

== Separability of the metric

The separability of the metric at any given point is trivial, if our spacetime is 
the manifold $MM$, by picking a coordinate system $x^i$ on a maximally symmetric
submanifold $EE$, this coordinate system can be extended to a global coordinate 
system by first picking a normal vector to the surface $n$. This can be done by 
taking the basis of $T_p EE$ generated by our coordinate system and then by 
Gram-Schmidt algorithm extend it to basis of $T_p MM$ and picking $n$ to be normal
to $EE$, this normal vector can be extended to a normal vector field by doing this
process at every point and making the field smooth forces an orientation.
After this the coordinate system $x^i$ can be extended by adding an 
additional coordinate $x^0$, that we will denote $t$, defined as the parameter
of the geodesics starting
at $x^i$ with initial four velocity $n$
#footnote[Here we are assuming geodesic completeness, this is fine because it is 
assumed that our space is complete and the Hopf-Rinow theorem, gives an 
equivalence between both statements.]. In this way the set of points of constant
$x^i$ is defined as the points that the geodesic goes through and as a time variable 
the arclength of the geodesic is chosen. An intuitive way to see this coordinate 
system is to imagine that we place an observer at each point of our surface and
assign a coordinate to each of them, after this we allow all of the observers to 
evolve and take as a time coordinate the time they measure with their clocks.

To check that the coordinate system we have actually has $g_(0 i) = 0$. A way to
check this would be by using that the Christoffel symbol $tensor(Gamma, -i 0 0)$ 
is related to the metric by

$ tensor(Gamma, -i 0 0) = 1/2 (2 partial_0 g_(0 i) - partial_i g_(0 0)) $

and since $g_(0 0) = norm(n)^2 = -1$ that means that 
$ tensor(Gamma, -i 0 0) = partial_0 g_(0 i) $

so that by proving that $tensor(Gamma, -i 0 0) = 0$, $g_(0 i) = 0$ is also proven.
To compute $tensor(Gamma, -i 0 0)$ we can use the geodesic equation and remember
that our coordinate system is defined by geodesics so that

$ dot.double(x)^i = 0 = -christoffel(i, mu, nu) dot(x)^mu dot(x)^nu = 
-christoffel(i, mu, nu) delta^mu_0 delta^nu_0 = -christoffel(i, 0, 0) =>\ =>
tensor(Gamma, -i 0 0) = 0 $.


Now that have a coordinate system that has the initial form we wanted.
Next, it is important to check that in this coordinate system all spatial slices
are maximally symmetric. Right now we have only assumed that the initial slice is
maximally symmetric, however that doesn't tell us anything about the structure of
all of the spatial slices. This is an interesting question because it could be the
case where some spaces start maximally symmetric but at some point they stop being
symmetric. As we will see this is not the case.

To do this first we extend the Killing vectors on the slice to Killing vectors
of all of space by the insertion map of the slice defined as

$ i(v^i) = (0, v^i) = v^mu $

So that the tangent vectors on the slice are tangent when mapped to the manifold.
Therefore in this coordinate system the Killing fields on the initial surface take
the following form $K^0(t = 0, x^i) = 0$. To check that the Killing fields are 
Killing fields in all of the constant time surfaces first we use the $(0, 0)$ 
component of the Killing equation

$ 2 g_(0 0) partial_0 K^0 + cancel(K^0 partial_0 g_(0 0)) = 0 => partial_0 K^0 = 0 $

This with the initial condition of $K^0(t = 0) = 0$ shows that the Killing fields
are tangent to constant time slices. 

Now we are close to proving that all spatial slices are maximally symmetric, since
the differential equation has unique solutions as long as the metric is enough
well behaved this looks like is enough to prove that the slices have the same 
number of Killing fields as the initial one, so they are maximally symmetric too.
However there is an edge case, that being whenever a Killing field becomes zero.
To prove this is not the case it is easy to use the $(0, i)$ components of the 
Killing equation.

$ cancel(K^alpha partial_alpha g_(0 i)) + cancel(g_(0 alpha) partial_i K^alpha)
+ g_(alpha i) partial_0 K^alpha = g_(j i) partial_0 K^j = 0 => partial_0 K^j = 0 $

The equality between the first and second expression might not be completely clear
unless one remembers that the spatial part of the metric is positive definite so
that in matrix it is a non-singular matrix. 

Just as before this implies that the spatial parts of the Killing vectors are 
constant in time. Therefore all slices are maximally symmetric.

To show that the spatial part has the form of $g_(i j) = a^2(T) h_(i j)$ where
$h_(i, j)$ is independent of time.

The path
it to use two properties of the Lie derivative with respect to a Killing field.

These are:
1. For any symmetric tensor $T_(alpha beta)$ in a maximally symmetric manifold
$ lie(K, T_(alpha beta)) = 0 => T_(alpha beta) = T/n g_(alpha beta) $<eq-cosm:sym-tensor-relationship-to-the-metric>
where $T:= tensor(T, -alpha, alpha)$ is the trace of the tensor and $n$ is the 
dimension of the space

2. In this coordinate system
$ lie(K, dot(g)_(i j)) = 0 $<eq-cosm:lieder-of-gdot>

and with these two facts the resulting differential equation has as a solution
$ g_(i j) = e^f(t) g_(i j)(t = 0) $

proving the form of the metric we expected.

Proving @eq-cosm:lieder-of-gdot is easy by direct computation

$ 0=dv(, t)(lie(K, g_(i j))) 
&= dv(, t)(K^alpha partial_alpha g_(i j) + 
g_(alpha j) partial_i K^alpha + g_(i alpha) partial_j K^alpha ) \

&= K^alpha partial_alpha dot(g)_(i j) + 
dot(g)_(alpha j) partial_i K^alpha + dot(g)_(i alpha) partial_j K^alpha \
&+ cancel(dot(K)^alpha partial_alpha g_(i j) + 
g_(alpha j) partial_i dot(K)^alpha + g_(i alpha) partial_j dot(K)^alpha ) 
\
&= lie(K, dot(g)_(i j))
 $


The @eq-cosm:sym-tensor-relationship-to-the-metric is proven by proving the 
stronger statement restricted to only isotropic manifolds. By choosing a rotation
around a point $K$ one has:

$ lie(K, T) = 
T_(gamma beta) partial_alpha K^gamma + T_(alpha gamma) partial_beta K^gamma + cancel(K^gamma partial_gamma T_(alpha beta)) 
=^(partial_alpha K^gamma = cdv(K^gamma, alpha))
tensor(T, gamma, -beta) partial_alpha K_gamma + tensor(T, -alpha, gamma) partial_beta K_gamma = 0  $

The last expression can be rewritten as

$ tensor(T, gamma, -beta) partial_alpha K_gamma + tensor(T, -alpha, gamma) partial_beta K_gamma =
(tensor(T, gamma, -beta) delta^sigma_alpha+tensor(T, -alpha, gamma) delta^sigma_beta) partial_sigma K_gamma = 0 $

since rotations are antisymmetric on $sigma$ and $gamma$ that means that

$ tensor(T, gamma, -beta) delta^sigma_alpha + tensor(T, -alpha, gamma) delta^sigma_beta =
tensor(T, sigma, -beta) delta^gamma_alpha + tensor(T, -alpha, sigma)delta^gamma_beta $

and by contracting $beta$ and $gamma$ the resulting expression is

$ n tensor(T, gamma, -beta) + tensor(T, -beta, gamma) = tensor(T, gamma, -beta) + delta^gamma_beta T =>
\ => (n-1)tensor(T, gamma, -beta) + tensor(T, -beta, gamma) = delta^gamma_beta T $


and finally by multiplying both sides by $g_(alpha gamma)$ the theorem is proven

$ (n-1) T_(beta alpha) + T_(alpha beta) = n T_(alpha beta) = g_(alpha beta) T $


Now that we know that the metric has the form

$ dd(s)^2 = -dd(t)^2 + a^2(t) h_(i j) dd(x)^i dd(x)^j $

the next step is to prove that maximally symmetric manifolds are constant curvature
spaces. By proving that they are we can apply the Killing-Hopf theorem and now the 
submanifolds are isometric to either flat space, a 3 hyperboloid or a 3 sphere. 
Allowing to get the components $h_(i j)$ and obtaining the final form of the metric.

But first we will introduce the notion of the sectional curvature.

== Sectional curvature and maximally symmetric spaces

Sectional curvature is defined as a generalization of Gaussian curvature. In $RR^3$
surfaces can be assigned a curvature that is related to the Riemann tensor by

$ R_(a b c d) = K (g_(a c) g_(b d) - g_(a d) g_(b c)) $<eq-cosm:constant-sectional-curvature-and-riemann-tensor>

by choosing two linearly independent vectors tangent to the surface $u$ and $v$
and multiplying both sides by $u^a v^b v^c u^d$ (the only non-zero combination of
two vectors)
one obtains

$ K = (R_(a b c d) u^a v^b v^c u^d)/(innerproduct(u, v)^2 - innerproduct(u, u) innerproduct(v, v)) $<eq-cosm:constant-sectional-curvature-definition>

generalizing this formula to any other space is easy just by making $K$ a 2-covariant
tensor so that it takes in two vectors and plugs them into 
@eq-cosm:constant-sectional-curvature-definition. The Killing-Hopf theorem states
that any pair of manifolds with constant sectional curvature are isometric if their
sectional curvatures are equal. So by proving that maximally symmetric spaces have
a Riemann tensor of the form @eq-cosm:constant-sectional-curvature-and-riemann-tensor
with constant $K$ will give us the metric on the spatial slices.

== Riemann tensor on maximally symmetric spaces

To obtain the form of the Riemann tensor we start from the fact that the Riemann 
tensor is intrinsic, therefore, the Lie derivative of the Riemann tensor with 
respect to one of the rotations at any given point must be zero. This gives the 
following equation

$ lie(K, R) &= cancel(K^alpha partial_alpha R_(mu nu gamma sigma)) 
+ R_(alpha nu gamma sigma) partial_mu K^alpha 
+ R_(mu alpha gamma sigma) partial_nu K^alpha
+ R_(mu nu alpha sigma) partial_gamma K^alpha
+ R_(mu nu gamma alpha) partial_delta K^alpha =\
&= 
  R_(alpha nu gamma sigma) partial_mu K^alpha 
- R_(alpha mu gamma sigma) partial_nu K^alpha 
+ R_(alpha sigma mu nu) partial_gamma K^alpha 
- R_(alpha gamma mu nu) partial_sigma K^alpha =\
#scale(100%, $(cdv(K, alpha) = partial_alpha K) / "for rotations"$)&=

  tensor(R, alpha, - nu gamma sigma) cdv(K_alpha, mu)
- tensor(R, alpha, - mu gamma sigma) cdv(K_alpha, nu)
+ tensor(R, alpha, - sigma mu nu) cdv(K_alpha, gamma)
- tensor(R, alpha, - gamma mu nu) cdv(K_alpha, sigma) =\
&= 
(
  tensor(R, alpha, - nu gamma sigma) delta^epsilon_mu
- tensor(R, alpha, - mu gamma sigma) delta^epsilon_nu
+ tensor(R, alpha, - sigma mu nu) delta^epsilon_gamma
- tensor(R, alpha, - gamma mu nu) delta^epsilon_sigma
) cdv(K_alpha, epsilon)=0
$

since the covariant derivative of a Killing field is antisymmetric this equation 
is solved for all of the rotations if and only if

$
  tensor(R, alpha, - nu gamma sigma) delta^epsilon_mu
- &tensor(R, alpha, - mu gamma sigma) delta^epsilon_nu
+ tensor(R, alpha, - sigma mu nu) delta^epsilon_gamma
- tensor(R, alpha, - gamma mu nu) delta^epsilon_sigma 
= \
&=
  tensor(R, epsilon, - nu gamma sigma) delta^alpha_mu
- tensor(R, epsilon, - mu gamma sigma) delta^alpha_nu
+ tensor(R, epsilon, - sigma mu nu) delta^alpha_gamma
- tensor(R, epsilon, - gamma mu nu) delta^alpha_sigma
$<ec-cosm:antisymmetry-riemann-tensor-lie-derivative>

The easiest way to obtain a relationship between the Riemann tensor and the metric
from here is to make contractions that give Ricci tensors. This is because since 
the Ricci tensor is intrinsic and symmetric by
@eq-cosm:sym-tensor-relationship-to-the-metric
$ R_(alpha beta) = R/n  g_(alpha beta) $<ec-cosm:ricci-metric-relation>

Contracting $epsilon$ and $mu$ gives

$ "LHS" &=  
  tensor(R, alpha, - nu gamma sigma) delta^mu_mu
- tensor(R, alpha, - mu gamma sigma) delta^mu_nu
+ tensor(R, alpha, - sigma mu nu) delta^mu_gamma
- tensor(R, alpha, - gamma mu nu) delta^mu_sigma \
&=
n tensor(R, alpha, - nu gamma sigma) 
- tensor(R, alpha, - nu gamma sigma)
+ tensor(R, alpha, - sigma gamma nu) 
- tensor(R, alpha, - gamma sigma nu)  \
&=
(n-1) tensor(R, alpha, - nu gamma sigma) 
+ underbrace(tensor(R, alpha, - sigma gamma nu) 
+ tensor(R, alpha, - gamma nu sigma), "Bianchi identity")  \
&=
(n-1) tensor(R, alpha, - nu gamma sigma) 
- tensor(R, alpha, - nu sigma gamma)

\ \
"RHS" &= 
  tensor(R, mu, - nu gamma sigma) delta^alpha_mu
- underbrace((tensor(R, mu, - mu gamma sigma) delta^alpha_nu), R_(alpha beta gamma sigma) = - R_(beta alpha gamma sigma))
+ tensor(R, mu, - sigma mu nu) delta^alpha_gamma
- tensor(R, mu, - gamma mu nu) delta^alpha_sigma \
&=
  tensor(R, alpha, - nu gamma sigma) 
+ tensor(R, - sigma nu) delta^alpha_gamma
- tensor(R, - gamma nu) delta^alpha_sigma \
&=
-  tensor(R, alpha, - nu sigma gamma) 
+ tensor(R, - sigma nu) delta^alpha_gamma
- tensor(R, - gamma nu) delta^alpha_sigma


\ \ 

"LHS" &= "RHS" + #[@ec-cosm:ricci-metric-relation]
 => \ &=>
tensor(R, alpha, - nu gamma sigma)  = 
R/(n(n-1)) (
  tensor(g, - sigma nu) delta^alpha_gamma
- tensor(g, - gamma nu) delta^alpha_sigma) =>\

dot g_(alpha beta)
&=> 
tensor(R, -beta nu gamma sigma) = R/(n(n-1)) (g_(sigma nu) g_(beta gamma) - g_(gamma nu) g_(beta sigma)

)
$

Our sectional curvature is $K = R/(n(n-1))$ and is independent of the orientation
of the surface. The only remaining fact to prove is that this is constant through 
space. To do this we use that the Ricci scalar is intrinsic and by taking the 
Lie derivative with respect to a translation 

$ lie(K, R) = K^alpha partial_alpha R = 0 $

therefore the sectional curvature is constant.

== Geodesics on the FLRW metric

The Killing fields on this space @killing-fields-FLRW are defined by
6 parameters $delta a_x, delta a_y, delta a_z, 
delta b_x, delta b_y$ and $delta b_z$ 
and their components are

$ 
xi^t &= 0\

xi^r &= sqrt(1-k r^2) (sin theta (cos phi.alt delta a_x + sin phi.alt delta a_y) + cos theta delta a_z)\

xi^theta &= sqrt(1-k r^2)/r [cos theta (cos phi.alt delta a_x + sin phi.alt delta a_y) - sin theta delta a_z] + (sin phi.alt delta b_x - cos phi.alt delta b_y)\

xi^phi.alt &= sqrt(1- k r^2)/r [1/sin(theta) (cos phi.alt delta a_y - sin phi.alt delta a_x)] +
cot theta (cos phi.alt delta b_x + sin phi.alt delta b_y) - delta b_z
$

Since the spatial slices are maximally symmetric we can work without the loose of 
generality in a coordinate system where the initial position is in the ray
defined by $theta = pi/2$ and $phi.alt = 0$ and the four-velocity has only a time 
and radial component. 

By choosing the Killing field generated by $delta arrow(a) = 0$ and $delta b_x = delta b_z = 0$ 
and $delta b_y = 1$, that we will denote $K$ the components of the Killing field are
$ K = -cos(phi.alt) partial_theta  $

therefore the conserved quantity

$ K_mu u^mu = - a^2(t) r sqrt(1 - k r^2) cos phi.alt u^theta = 0 $

enforces $u^theta = 0$ for all time as long as $phi.alt != pm pi/2$.

Similarly by taking $delta arrow(a) = 0$ and $delta b_x = delta b_y = 0$ $delta b_z = -1 $
and calling this Killing field $omega$ we find that

$ omega = sqrt(1-k r^2)/r partial_phi.alt $

giving as a conserved quantity

$ omega_mu u^mu = a^2(t) r sqrt(1- k r^2) sin theta u^phi.alt = 0 $

therefore once again $u^phi.alt = 0$ as long as $theta != n pi$  with $n in ZZ$.

With these two conditions we can see that the $theta "and" phi.alt$ components 
will be constants. This leaves us with the choice of $delta a_x = 1$, $delta a_y = delta a_z = delta arrow(b) = 0 $  giving the Killing field we will denote $Xi$ that can be written as

$ Xi = sqrt(1-k r^2) partial_r $

and the associated conserved quantity is

$ P = Xi_mu u^mu = a^2 (t) u^r $<ec-cosm:conservation-of-ur>

This, already gives an interesting result. By inspecting the metric it might seem
like for $k = 1$ (spherical universes) the surface at $r = 1$ is some kind of event
horizon and that $u^r -> 0$ preventing matter or light from crossing it. However
as we see in @ec-cosm:conservation-of-ur this is not the case. The reason for this
is that the $r$ coordinate chosen here would be the equivalent to the distance from
some point on a sphere to the $z$ axis. And the region at $r = 1$ would be the 
equator. The apparent singularity appears because close to the equator the distance
to the z axis is constant, not allowing $r$ to be a valid variable.

By also using the condition of the normalization of $u$ we can obtain following differential equation

$ dv(r, t) = u^r/u^t = u^r/sqrt(1+ (a^2(t))/sqrt(1- k r^2) (u^r)^2 ) 
= (P a^(-2))/sqrt(1+ P^2 (a^(-2)(t))/sqrt(1- k r^2)) = P/sqrt(a^4 (t) + (P^2 a^2(t))/sqrt(1 - k r^2)) $

as we can see as the universe increases in size matter slows down since as $a$ 
increases $dv(r, t)$ decreases.