#import "../things-to-add.typ": *

= Computation of redshifts

So far we have been talking about the geodesics and how Killing fields generate 
conserved quantities, in particular we have seen that when there is a time-like 
Killing field we can define energy for particles. It would be nice if we could 
extend this idea to photons, and since photon energy is related to the frequency
obtain gravitational redshifts with it. However there is a big problem with this
approach, photons don't have mass. This means that there isn't a linear relation 
between their four-velocity and four-momentum, thus there isn't any affine 
parametrization that has four-momentum as a tangent vector.

Fortunately for us there is a way to relate time-like Killing fields to redshifts
in a more roundabout way.

Imagine we have two observers, Alice and Bob. Alice is emitting light from the 
curve#footnote[Since observers move through time.] $x^mu_a (tau)$ to Bob, 
who is in curve $x^mu_b (tau)$. To compute the redshift we would
need to compute the quotient of the frequencies measured from Bob and Alice 
perspective, so the redshift $z$ will be defined as

$ 1+z = lambda_B/lambda_A = f_A/f_B = T_B/T_A $

where $lambda$ are the wavelengths measured by Alice and bob, $f$ the frequencies
and $T$ the periods.

The usual recipe to compute redshifts is based on the period. To compute these 
one usually takes two null geodesics emitted from $x^mu_A$ and separated by a 
proper time $T_A$ and arrive to $x^mu_B$ with a proper time separation of $T_B$.

This is good approach but requires to know the expression for null geodesics, this
can be solved if we have a time-like Killing field.

Assume we have a time-like Killing field $K$. Now we define stationary observers
as those whose four-velocity is proportional to $K$. If we wanted to compute a 
redshift for an observer who is not stationary we can use the lorentz doppler effect
combined with the gravitational redshift by using the redshift combination formula

$ 1+z_t = (1+z_L)(1+z_g) $ 

Now, lets say we have two stationary observers $A$ and $B$ at positions $A_0$ and 
$B_0$ connected by a null geodesic. After a time, $T_A$ measured by $A$ another 
geodesic is emitted, representing the next wavefront of light that will touch the
observer $B$ at a different time. What we did here is change the positions of the
observers from $A_0 -> A_0 + u_A Delta tau$ and $B_0 -> B_0 + u_B Delta tau$ 
representing the time evolution of the observers. However,
since the four-velocities are proportional to the Killing field, 
this can be recreated by using the isometry generated by $K$. Additionally since
both points are connected by a null geodesic at the initial time and geodesics are
intrinsic we are guaranteed that both points will be connected by null geodesics 
when transformed by the isometry. Thus the proper time difference
measured by $A$ or $B$,
approximating that the four-momentum is constant for both observers in the time 
range of measurement,  is 

$ T_(A slash B) = sqrt(pm (u_(A slash B))_mu (u_(A slash B))^mu) Delta tau $

where the $pm$ depends on the signature. By substituting $u_(A slash B) prop K$
because our observers are stationary.

$ T_(A slash B) = alpha Delta tau sqrt(pm K_mu K^mu)  $

so that the redshift can be computed as

$ 1+z = sqrt((K_mu (B_0) K^mu (B_0))/(K_mu (A_0) K^mu (A_0))) $

In the case of the of the schwarzschild metric we obtain the well known formula

$ 1+z = sqrt((g_(0 0) (B))/(g_(0 0) (A))) $<ec-redshift:killing-redshift>

this also applies for the Kerr black hole, however an interesting result comes 
out. With this formula the border of the ergosphere is an infinite redshift 
surface. This is surprising because we saw that this surface is not an event 
horizon and we should be able to see through it. The problem here is on the 
definition of stationary observer, we are picking as a stationary observer, 
someone that 
doesn't rotate with the black hole. Inside the ergosphere that means someone 
spinning faster than light, thus by a Lorentz doppler effect we get an infinite 
redshift. The trick here is to use a combination of the time and axial Killing 
fields $K = partial_t + Omega_H partial_phi$ where $Omega_H$ makes it so that the 
Killing field is null at the exterior event horizon. This way stationary observers
do rotate with the black hole giving a finite redshift between the interior and
exterior regions of the ergosphere.

In the case of the FLRW metric, there isn't a time-like Killing field. However there
is a way to extend this kind of method by introducing the so called *Homothetic
Killing fields*. This kind of field represents an expansion and its defined by 

$ lie(H, g) = kappa g $

where $kappa$ is some constant. This kinds of fields also preserve geodesics, this
is because the geodesic action

$ S = integral g_(mu nu) dot(x)^mu (tau) dot(x)^nu dd(tau) $

under the transformation generated by $H$ is transformed as $S -> S' = kappa S$.
Therefore the extreme points don't change because $delta S' = 0 <=> delta S = 0$.

In the case of the FLRW metric there is one Homothetic Killing field 
$ H = a(t) partial_t $

that after applying @ec-redshift:killing-redshift the resulting redshift is 

$ 1+z = a(B)/a(A) $
