#import "../things-to-add.typ": *

= Optics

Classical geometrical optics treat light as rays that move at a certain speed and
bend by Snell law. General relativity treats light rays in a similar way but uses
geodesics to shape their path. Treating geometrical optics as an effective theory
of general relativity gives an insight on the origin of the Snell law.

In some medium, because of the light matter interactions, light moves at a speed
different from the one it would have when left unperturbed. This is usually 
modelled by assigning a number to each material called index of refraction 
defined as 

$ n = c/v $ 

where $v$ is the speed of light on the medium. 

In general relativity the speed of light is obtained by the condition of the 
four-velocity of the light being a null vector. This allows to give an index of 
refraction to each point in spacetime by using the following metric

$ dd(s)^2 = c^2 dd(t)^2 - n^2 (dd(x)^2 + dd(y)^2 + dd(z)^2) $

as it can be seen the speed of light in any of the three cartesian 
directions is 

$ c^2 dd(t)^2 - n^2 dd(x)^2 = 0 => dd(x)^2/dd(t)^2 = c^2/n^2 = v^2  $

as expected.

First lets start with a simple case where we have some material on one side and
vacuum on the other. To do this we will pick 

$ n(x) = n theta(x) $

where $theta$ is the Heaviside function.

It is easy to see that for this space there are four Killing fields.

$ T &= partial_t \
  Y &= -partial_y\
  Z &= -partial_z \
  omega &= -z partial_y +y partial_z $

Y and Z allow to shift both the $y$ and $z$ coordinates and $omega$ generates 
rotations on $y$ and $z$ coordinates, thus without loosing generality we will 
pick the light ray to start with $u^z = 0$. This condition remains valid for all
of the path of the light ray since the conserved quantity generated by $Z$ is 
$n u^z$ and since it starts being zero it requires $u^z = 0$ for all time.

The conserved quantities generated by $T$ and $Y$ are

$ 
  T_mu u^mu = c^2 u^0\
  Y_mu u^mu = n^2 u^y
$

Since combinations of conserved quantities is also conserved we can see that the 
quantity 

$ cal(S) =  n^2/c^2 dv(y, t) = 1/v^2 dv(y, t) $

is conserved. Since the spacial part of the metric is euclidean $dv(y, t)$ is 
equivalent to the classical $y$ component of the velocity of the light ray.
Therefore 

$ dv(y, t) = v sin(theta) $ 

where $theta$ is the classical angle between the light ray direction and the $x$
axis. After making this substitution we get

$ cal(S) = sin(theta)/v $

Since this is conserved, it is equal on the vacuum and the material. Therefore
by making the equality on both sides and multiplying by $c$ we get Snell's law

$ n_1 sin(theta_1) = n_2 sin(theta_2) $

This argument can also be extended to other geometries since, close to the point
of contact of the light ray with the boundary, by taking a small enough 
neighborhood of the contact point the surface will be flat and the same three 
Killing fields will be valid giving the same law.

This also allows us to work on more complex results. 

As an example for moving matter along 
the x axis with with speed $beta = v/c$.  
By using special relativity we can do a Lorentz transformation on the stationary
reference frame to obtain the equations when the block moves. By calling 
the frame where block moves $x'^mu$ and the frame where the matter doesn't move.

The Lorentz transformation in this case is 

$ 
  cases(c t &= gamma (c t' - beta x'), x &= gamma (x' - beta c t'), y&=y', z&=z'  )
$

The first quantity we are interested in is the norm of the four-velocity witch 
can be Lorentz transformed to give

$ 
  gamma^2(c u'^t - beta u'^x)^2 - n^2(gamma^2 (u'^x - beta c u'^t)^2 + (u'^y)^2) =\
  gamma^2 c^2 (1-beta^2n^2) (u'^t)^2 + 2 beta c gamma^2(n^2-1)u'^t u'^x + 
  gamma^2 (beta^2 - n^2)(u'^x)^2 - n^2 (u'^y)^2 = 0
$

As we can see the resulting material behaves as if it was anisotropic, by defining

$ 
  dv(x', t') = v'(theta') cos(theta')\ 
  dv(y', t') = v'(theta') sin(theta')
$

We can obtain the speed of light depending on the direction, the resulting 
expression is

$ 
  v'(theta') = (2 beta c (n^2 -1)cos(theta') pm sqrt(Delta(theta')))/(2 (gamma^2 (n^2 - beta^2) cos^2(theta') + n^2 sin^2(theta')))
  
  \
  Delta(theta') = 2 beta c (n^2 -1) cos^2(theta') 
          + 4c^2 gamma^2 (1-n^2 beta^2) (gamma^2(n^2-beta^2) cos^2(theta') +n^2 sin^2(theta')
$

Restricting to only positive solutions of $v$ we see that there are two cases. 

The range where $beta^2 > 1/n^2$ and the range where $beta^2 < 1/n^2$.

If the material moves more slowly than the light rays all angles of movement are 
allowed. However light tends to go faster in the direction of the material. On the
other hand when the material goes faster than the light inside of it only certain
$theta'$ are allowed. This is because the material is dragged with the material 
similarly how black holes drag light when moving or when rotating.

To obtain the equivalent to Snell law in this frame of reference we can Lorentz
boost the Killing fields obtaining

$ 
  [T'_mu] &= (c^2 gamma, -beta c gamma, 0, 0)\
  [Y'_mu] &= (0, 0, n^2, 0)
$

And by the same process as the one used to find $cal(S)$

$ 
  cal(S') = (n^2 u'^y)/(c^2 gamma (u'^t - beta/c u'^x)) = 
  (n^2 u'^y)/(c^2 gamma u^t (1 - beta/c v'(theta') cos(theta'))) = 
  sin(theta')/(v'(theta') gamma (1-beta/c v'(theta') cos(theta')) )
$

